### ISSUE TITLE
SETUP Kanban board

### ISSUE THREAD

**Issue by ichala** [ichala/short-let-api#16]
Hello!
We are a group of 5 persons, Our Team members are : 
@aimalamiri @d2ndjim @ichala @EidHachem @LYANGEND 

this is the link to the kanban board https://github.com/users/ichala/projects/5 
this is the link to the front-end [issues](https://github.com/ichala/short-let-frontend/issues)
this is the link to the back-end [issues](https://github.com/ichala/short-let-api/issues)

![DailySoccer drawio](https://user-images.githubusercontent.com/89282221/190204556-3ebaab40-4bbd-4f70-b450-27a2fcc5e99e.png)

Screenshot of the kanban board

![kannnnnnnnnnnnnn](https://user-images.githubusercontent.com/89282221/190205252-fd7bdeee-a2f2-4bc2-add9-e8efe93b9d51.gif)

**Comment by mcrd25** [comment]
Hi team, 

Good job so far!
There are some issues that you still need to work on 



## Suggested changes

- Each card should have number of pts associated - I do not see this for each card (I do see that some of it is a group activity but you should still add the pts/hrs associated with it


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  


Good luck! 🎉 


Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.
